In [1]:
import pandas as pd

In [3]:
df = pd.read_excel("data.xlsx")
df.head()

        Date   Country Product  Sales     Category Region
0 2023-01-01       DRC       A  446.0         Food  North
1 2023-01-02  Tanzania       C   56.0  Electronics  South
2 2023-01-03    Uganda       C   65.0     Clothing  South
3 2023-01-04     Kenya       B  364.0     Clothing   West
4 2023-01-05     Kenya       C  260.0  Electronics   West

In [14]:
pivot_table = df.pivot_table(index = 'Country',columns= 'Product',values= 'Sales',aggfunc='sum')
pivot_table

Product        A       B       C
Country
DRC        868.0   553.0   924.0
Kenya     1117.0  1304.0  1562.0
Tanzania   461.0  2478.0  1205.0
Uganda     670.0   133.0   509.0

In [22]:
pivot_table2 = df.pivot_table(
index=['Country','Category'],#multiple index columns
columns=['Product'],#multiple columns for products
values=['Sales'],#values to aggregate
aggfunc=['sum','mean','max']#multiple aggregation functions
)
pivot_table2

                        sum                       mean              \
                      Sales                      Sales
Product                   A       B      C           A           B
Country  Category
DRC      Clothing     233.0   553.0    NaN  233.000000  276.500000
         Electronics  189.0     NaN   65.0   94.500000         NaN
         Food         446.0     NaN  859.0  446.000000         NaN
Kenya    Clothing     356.0   364.0  456.0  356.000000  364.000000
         Electronics  578.0     NaN  972.0  192.666667         NaN
         Food         183.0   940.0  134.0  183.000000  313.333333
Tanzania Clothing       NaN   644.0  310.0         NaN  322.000000
         Electronics  409.0  1132.0  895.0  204.500000  377.333333
         Food          52.0   702.0    NaN   52.000000  234.000000
Uganda   Clothing       NaN     NaN   65.0         NaN         NaN
         Electronics  477.0   133.0  444.0  477.000000  133.000000
         Food         193.0     NaN    NaN  193.000000         NaN

                                    max
                                  Sales
Product                        C      A      B      C
Country  Category
DRC      Clothing            NaN  233.0  418.0    NaN
         Electronics   65.000000  124.0    NaN   65.0
         Food         429.500000  446.0    NaN  488.0
Kenya    Clothing     228.000000  356.0  364.0  313.0
         Electronics  324.000000  315.0    NaN  474.0
         Food         134.000000  183.0  400.0  134.0
Tanzania Clothing     310.000000    NaN  430.0  310.0
         Electronics  298.333333  312.0  472.0  486.0
         Food                NaN   52.0  302.0    NaN
Uganda   Clothing      65.000000    NaN    NaN   65.0
         Electronics  444.000000  477.0  133.0  444.0
         Food                NaN  193.0    NaN    NaN

In [44]:
pivot_table.sort_values(by="A",ascending =False) #sorting values in ascending order by product A

Product        A       B       C
Country
Kenya     1117.0  1304.0  1562.0
DRC        868.0   553.0   924.0
Uganda     670.0   133.0   509.0
Tanzania   461.0  2478.0  1205.0

In [48]:
additional_data = pd.DataFrame({
'Country': ['Kenya','Uganda','Tanzania'],
 'GDP':[21,1.7,4.2],
})
additional_data

    Country   GDP
0     Kenya  21.0
1    Uganda   1.7
2  Tanzania   4.2

In [56]:
merged_df = pd.merge(df,additional_data, on='Country',how='left')
merged_df.head()

        Date   Country Product  Sales     Category Region   GDP
0 2023-01-01       DRC       A  446.0         Food  North   NaN
1 2023-01-02  Tanzania       C   56.0  Electronics  South   4.2
2 2023-01-03    Uganda       C   65.0     Clothing  South   1.7
3 2023-01-04     Kenya       B  364.0     Clothing   West  21.0
4 2023-01-05     Kenya       C  260.0  Electronics   West  21.0

In [58]:
merged_df = pd.merge(df,additional_data, on='Country',how='right')
merged_df.head()

        Date Country Product  Sales     Category Region   GDP
0 2023-01-04   Kenya       B  364.0     Clothing   West  21.0
1 2023-01-05   Kenya       C  260.0  Electronics   West  21.0
2 2023-01-07   Kenya       C    NaN  Electronics   West  21.0
3 2023-01-08   Kenya       C    NaN         Food   East  21.0
4 2023-01-09   Kenya       A    NaN  Electronics  North  21.0

In [64]:
additional_data = pd.DataFrame({
'Country': ['Kenya','Uganda','Tanzania','Rwanda'],
 'GDP':[21,1.7,4.2,3.0],
})
additional_data

    Country   GDP
0     Kenya  21.0
1    Uganda   1.7
2  Tanzania   4.2
3    Rwanda   3.0

In [66]:
#merge the original dataset with additional data based on 'Country' (common dataset)
merged_df = pd.merge(df,additional_data, on='Country',how='left')
merged_df.head()

        Date   Country Product  Sales     Category Region   GDP
0 2023-01-01       DRC       A  446.0         Food  North   NaN
1 2023-01-02  Tanzania       C   56.0  Electronics  South   4.2
2 2023-01-03    Uganda       C   65.0     Clothing  South   1.7
3 2023-01-04     Kenya       B  364.0     Clothing   West  21.0
4 2023-01-05     Kenya       C  260.0  Electronics   West  21.0

In [68]:
merged_df = pd.merge(df,additional_data, on='Country',how='right')
merged_df.head()

        Date Country Product  Sales     Category Region   GDP
0 2023-01-04   Kenya       B  364.0     Clothing   West  21.0
1 2023-01-05   Kenya       C  260.0  Electronics   West  21.0
2 2023-01-07   Kenya       C    NaN  Electronics   West  21.0
3 2023-01-08   Kenya       C    NaN         Food   East  21.0
4 2023-01-09   Kenya       A    NaN  Electronics  North  21.0

In [87]:
 #joining the two table df
df.set_index('Country').join(additional_data.set_index('Country'))

               Date Product  Sales     Category Region   GDP
Country
DRC      2023-01-01       A  446.0         Food  North   NaN
Tanzania 2023-01-02       C   56.0  Electronics  South   4.2
Uganda   2023-01-03       C   65.0     Clothing  South   1.7
Kenya    2023-01-04       B  364.0     Clothing   West  21.0
Kenya    2023-01-05       C  260.0  Electronics   West  21.0
DRC      2023-01-06       A    NaN  Electronics  South   NaN
Kenya    2023-01-07       C    NaN  Electronics   West  21.0
Kenya    2023-01-08       C    NaN         Food   East  21.0
Kenya    2023-01-09       A    NaN  Electronics  North  21.0
Uganda   2023-01-10       C    NaN  Electronics  South   1.7
DRC      2023-01-11       A    NaN     Clothing   West   NaN
Kenya    2023-01-12       B  377.0         Food  North  21.0
Tanzania 2023-01-13       A   52.0         Food  South   4.2
DRC      2023-01-14       C  371.0         Food   East   NaN
Kenya    2023-01-15       A  356.0     Clothing   West  21.0
Kenya    2023-01-16       A  183.0         Food   West  21.0
Kenya    2023-01-17       C  474.0  Electronics   East  21.0
Uganda   2023-01-18       A  477.0  Electronics  South   1.7
Uganda   2023-01-19       B  133.0  Electronics   West   1.7
Kenya    2023-01-20       B  400.0         Food   West  21.0
Tanzania 2023-01-21       B  389.0  Electronics  North   4.2
Tanzania 2023-01-22       C  486.0  Electronics  North   4.2
Tanzania 2023-01-23       B  472.0  Electronics  South   4.2
Kenya    2023-01-24       A  315.0  Electronics   East  21.0
Kenya    2023-01-25       C  313.0     Clothing   East  21.0
Uganda   2023-01-26       C  444.0  Electronics   West   1.7
DRC      2023-01-27       C   65.0  Electronics   West   NaN
Tanzania 2023-01-28       C  310.0     Clothing  North   4.2
Uganda   2023-01-29       A  193.0         Food   East   1.7
Tanzania 2023-01-30       B  143.0         Food  South   4.2
Tanzania 2023-01-31       B  271.0  Electronics  South   4.2
Tanzania 2023-02-01       C  353.0  Electronics  South   4.2
DRC      2023-02-02       C  488.0         Food  North   NaN
DRC      2023-02-03       B  135.0     Clothing  South   NaN
Kenya    2023-02-04       A  193.0  Electronics   West  21.0
DRC      2023-02-05       B  418.0     Clothing   East   NaN
Kenya    2023-02-06       C  134.0         Food  South  21.0
Kenya    2023-02-07       C  143.0     Clothing  South  21.0
DRC      2023-02-08       A  233.0     Clothing  North   NaN
Kenya    2023-02-09       C  238.0  Electronics  South  21.0
Tanzania 2023-02-10       B  430.0     Clothing   West   4.2
Tanzania 2023-02-11       B  214.0     Clothing  North   4.2
Tanzania 2023-02-12       B  257.0         Food   East   4.2
Tanzania 2023-02-13       B  302.0         Food  North   4.2
DRC      2023-02-14       A  124.0  Electronics  North   NaN
Kenya    2023-02-15       B  163.0         Food   East  21.0
Kenya    2023-02-16       A   70.0  Electronics   East  21.0
Tanzania 2023-02-17       A  312.0  Electronics   East   4.2
DRC      2023-02-18       A   65.0  Electronics  South   NaN
Tanzania 2023-02-19       A   97.0  Electronics  North   4.2